{
    "id": "/sourcegraph/server",
    "cmd": null,
    "cpus": 2,
    "mem": 2048,
    "disk": 0,
    "gpus": 0,
    "instances": 1,
    "executor": "",
    "requirePorts": false,
    "constraints": [
        [
            "secrets",
            "LIKE",
            "true"
        ],
    ],
    "acceptedResourceRoles": ['*'],
    "container": {
        "type": "DOCKER",
        "volumes": [
            {
                "containerPath": "/etc/sourcegraph",
                "hostPath": "/opt/share/docker/secrets/sourcegraph",
                "mode": "RW"
            },
            {
                "containerPath": "/var/opt/sourcegraph",
                "hostPath": "/opt/share/docker/sourcegraph",
                "mode": "RW"
            }
        ],
        "docker": {
            "image": "sourcegraph/server:3.0.1",
            "privileged": false,
            "parameters": [
                {
                    "key": "env-file",
                    "value": "/opt/share/docker/secrets/sourcegraph/env-file"
                }
            ],
            "forcePullImage": false
        },
        "portMappings": [
            {
                "containerPort": 7080,
                "hostPort": 0,
                "servicePort": 10012,
                "protocol": "tcp",
                "name": "main",
                "labels": {}
            }
        ]
    },
    "networks": [
        {
            "mode": "container/bridge"
        }
    ],
    "healthChecks": [
        {
            "path": "/",
            "protocol": "MESOS_HTTP",
            "portIndex": 0,
            "delaySeconds": 15,
            "gracePeriodSeconds": 300,
            "intervalSeconds": 60,
            "timeoutSeconds": 20,
            "maxConsecutiveFailures": 3,
            "ipProtocol": "IPv4",
        }
    ],
    "labels": {
        "HAPROXY_GROUP": "lb"
    },
    "maxLaunchDelaySeconds": 3600,
    "backoffFactor": 1.15,
    "backoffSeconds": 1,
    "upgradeStrategy": {
        "minimumHealthCapacity": 1,
        "maximumOverCapacity": 1,
    },
    "killSelection": 'YOUNGEST_FIRST',
    "unreachableStrategy": {
        "inactiveAfterSeconds": 300,
        "expungeAfterSeconds": 600,
    },
}
