{
    "id": "/ocfweb/web",
    "cmd": null,
    "cpus": 1,
    "mem": 1024,
    "disk": 0,
    "gpus": 0,
    "instances": 3,
    "executor": "",
    "requirePorts": false,
    "constraints": [
        [
            "secrets",
            "LIKE",
            "true"
        ],
    ],
    "container": {
        "type": "DOCKER",
        "volumes": [
            {
                "containerPath": "/etc/ocfweb",
                "hostPath": "/opt/share/docker/secrets/ocfweb",
                "mode": "RO"
            },
            {
                "containerPath": "/etc/ocf",
                "hostPath": "/etc/ocf",
                "mode": "RO"
            }
        ],
        "docker": {
            "image": "docker.ocf.berkeley.edu/ocfweb-web",
            "privileged": false,
            "parameters": [],
            "forcePullImage": false
        },
        "portMappings": [
            {
                "containerPort": 8000,
                "hostPort": 0,
                "servicePort": 10002,
                "protocol": "tcp",
                "name": "main",
                "labels": {}
            }
        ]
    },
    "networks": [
        {
            "mode": "container/bridge"
        }
    ],
    "env": {
        "OCFWEB_TESTING": "0"
    },
    "healthChecks": [
        {
            "protocol": "COMMAND",
            "command": {
                "value": "curl -f -o /dev/null -H 'Host: www.ocf.berkeley.edu' http://$HOST:$PORT0/"
            },
            "delaySeconds": 15,
            "gracePeriodSeconds": 300,
            "intervalSeconds": 60,
            "timeoutSeconds": 20,
            "maxConsecutiveFailures": 3,
            "ipProtocol": "IPv4",
        }
    ],
    "labels": {
        "HAPROXY_GROUP": "lb"
    },
    "maxLaunchDelaySeconds": 3600,
    "backoffFactor": 1.15,
    "backoffSeconds": 1,
    "upgradeStrategy": {
        "minimumHealthCapacity": 1,
        "maximumOverCapacity": 1,
    },
    "killSelection": 'YOUNGEST_FIRST',
    "unreachableStrategy": {
        "inactiveAfterSeconds": 300,
        "expungeAfterSeconds": 600,
    },
    "acceptedResourceRoles": ['*'],
}
